name: Auto Merge Upstream PRs

on:
  workflow_dispatch:

jobs:
  merge-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: 'master'
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Fetch and Merge Unmerged PRs from Upstream
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "Adding upstream repository..."
          git remote add upstream https://github.com/dylanaraps/neofetch.git
          git fetch upstream
          
          echo "Checking for open pull requests..."
          prs=$(gh pr list -R dylanaraps/neofetch --json number --jq '.[].number')
          echo "Found open PRs: $prs"

          for pr in $prs; do
            echo "Attempting to merge PR #$pr from upstream..."
            git fetch upstream pull/$pr/head:pr-$pr
            git checkout master
            set +e  # Disable error stopping
            git merge --no-ff --log pr-$pr
            MERGE_STATUS=$?
            set -e  # Re-enable error stopping
            if [ $MERGE_STATUS -eq 0 ]; then
              echo "Successfully merged PR #$pr"
              git push origin master
            else
              echo "Conflicts while merging PR #$pr, skipping..."
              git merge --abort
            fi
            git checkout master  # Ensure back on master for next iteration
          done
